plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'org.jetbrains.kotlin.kapt'
}

android {
    namespace 'com.nagram.usbbridge'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nagram.usbbridge'
        minSdk 26
        targetSdk 35
        versionCode 16
        versionName '4.0.0-alpha01-m0a'
    }

    flavorDimensions += 'distribution'
    productFlavors {
        direct {
            dimension 'distribution'
            buildConfigField 'String', 'DISTRIBUTION', '"DIRECT"'
        }
        playStore {
            dimension 'distribution'
            buildConfigField 'String', 'DISTRIBUTION', '"PLAY_STORE"'
        }
    }

    buildFeatures {
        aidl true
        compose true
        buildConfig true
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    packaging {
        resources.excludes += '/META-INF/{AL2.0,LGPL2.1}'
    }
}

kapt {
    correctErrorTypes true
    arguments {
        arg("room.schemaLocation", "$projectDir/schemas")
    }
}

dependencies {
    def shizuku_version = '13.1.5'
    def compose_bom = platform('androidx.compose:compose-bom:2024.10.01')

    implementation "dev.rikka.shizuku:api:$shizuku_version"
    implementation "dev.rikka.shizuku:provider:$shizuku_version"
    implementation 'androidx.annotation:annotation:1.8.2'

    implementation compose_bom
    androidTestImplementation compose_bom
    implementation 'androidx.activity:activity-compose:1.9.3'
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    debugImplementation 'androidx.compose.ui:ui-tooling'

    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'

    implementation 'androidx.navigation:navigation-compose:2.8.4'

    implementation 'androidx.room:room-runtime:2.6.1'
    implementation 'androidx.room:room-ktx:2.6.1'
    kapt 'androidx.room:room-compiler:2.6.1'

    implementation 'androidx.work:work-runtime-ktx:2.10.0'
}
